### ISSUE TITLE
Create a web config system app

### ISSUE THREAD

**Issue by touchpi** [touchpi/touchpi#21]
After EOL of Debian LTS, we moved touchpi default development environment to Bullseye.
With this change in touchpi release Beta 0.5.0 the python development version changed from python 3.6 to python 3.9.
This change allow using python packages like NiceGUI for web devlopment.
This issue propose to change the old shellscript based config editor in the scripts folder to a more modern web based config editor.
Optional it would be nice to implement this feature as backend app.
requirement.txt for niceguy should reflect this. The app should not run as default and can be added optional in _core_apps.
After adding this feature it is a good startpoint to update the documentation for configure touchpi and developing apps.

**Comment by touchpi** [comment]
@merlin1996 please develop in your fork to test development process

**Comment by merlinbaer** [comment]
An upload of all local toml files in a zip file as backup would be a nice feature too
